---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: hass
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.0.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.115.3
    extraEnv:
      TZ: "Europe/London"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - "ha.i.lan"
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.30
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    vscode:
      enabled: false
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 35m
        memory: 800Mi
    monitoring:
      enabled: false
