---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: cert-manager
  rollback:
    enable: false
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.16.1
  values:
    webhook:
      enabled: true
    ingressShim:
      defaultIssuerName: letsencrypt-staging
      defaultIssuerKind: ClusterIssuer
#     # Enabled once prometheus-operator is installed
#     prometheus:
#       enabled: true
#       servicemonitor:
#         enabled: true
#         namespace: cert-manager
