helmOperator:
  create: false
git:
  url: "git@github.com:vaskozl/dou-ops.git"
  branch: master
  path: deployments
image:
  repository: raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
# Enabled once prometheus-operator is installed
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
