---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  releaseName: pihole
  chart:
    repository: https://mojo2600.github.io/pihole-kubernetes/
    name: pihole
    version: 1.7.15
  values:
    serviceTCP:
      loadBalancerIP: 192.168.1.16
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceUDP:
      loadBalancerIP: 192.168.1.16
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    dnsmasq:
      additionalHostsEntries:
      # Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
        - 192.168.1.16     pihole.lan pi.hole
        - 192.168.1.181    pi0.lan
        - 192.168.1.11     pi1.lan
        - 192.168.1.72     pi2.lan
        - 192.168.1.17     gitea.lan
        - 192.168.1.18     i.lan

    persistentVolumeClaim:
      enabled: true
    #TODO: Secure pihole
    adminPassword: admin
