---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  releaseName: gitea
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://dl.gitea.io/charts/
    name: gitea
    version: 1.4.2
  values:
    image:
      repository: gitea/gitea
      tag: linux-arm64
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "git.i.lan"
      tls:
      - hosts:
        - "git.i.lan"
    service:
      ssh:
        loadBalancerIP: 192.168.1.17
        port: 22
    gitea:
      config:
        APP_NAME: "Doudous' Gitea"
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
      database:
        builtIn:
          postgresql:
            enabled: true
    postgresql:
      etrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: default
