---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: gitea
  helmVersion: v3
  chart:
    repository: https://dl.gitea.io/charts/
    name: gitea
    version: 1.4.2
  values:
    image:
      repository: gitea/gitea
      tag: latest-arm64
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "git.i.lan"
      tls:
      - hosts:
        - "git.i.lan"
    service:
      ssh:
        loadBalancerIP: 192.168.1.17
        port: 22
