---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: qbittorrent
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: qbittorrent
    version: 4.0.1
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls90
    timezone: "Europe/London"
    puid: 1000
    pgid: 1000
    umask: "022"
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.19
    btService:
      type: LoadBalancer
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "qb.pi.sko.ai"
      tls:
      - hosts:
        - "qb.pi.sko.ai"
        secretName: ingress-cert-qbittorrent
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        size: 2Gi
      downloads:
        enabled: false
      extraMounts:
      - name: media
        claimName: nfs-media-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 6000Mi
