---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  releaseName: nextcloud
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://nextcloud.github.io/helm
    name: nextcloud
    version: 2.2.0
  values:
    # Image actually runs it on port 80
    service:
      type: ClusterIP
      port: 80
    livenessProbe:
      initialDelaySeconds: 100
    readinessProbe:
      initialDelaySeconds: 100
    image:
      repository: nextcloud
      tag: 19.0.3-apache
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "nc.sko.ai"
      - "nc.i.lan"
      tls:
      - hosts:
        - "nc.sko.ai"
        secretName: ingress-cert-nc
    nextcloud:
      host: "nc.sko.ai"
    persistence:
      enabled: true
      storageClass: "nfs-client"
      s3000ize: 8Gi

