---

- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  #
  # @CHANGEME - Review each task to make sure it's doing what you want to do
  #
  tasks:
    - name: Unmount /dev/sda
      mount:
        path: /k3s-local-storage
        src: /dev/sda
        state: absent
      ignore_errors: true

    - name: Wipe /dev/sda
      command: wipefs -af /dev/sda
      register: wipefs
      changed_when: '"filesystem" in wipefs.stdout'

    - name: Create an EXT4 filesystem on /dev/sda
      filesystem:
        fstype: ext4
        dev: /dev/sda

    - name: Create k3s local storage directory
      file:
        path: /k3s-local-storage
        group: "users"
        owner: "{{ ansible_user }}"
        state: directory

    - name: Mount k3s local storage directory
      mount:
        path: /k3s-local-storage
        src: /dev/sda
        fstype: ext4
        opts: rw,defaults
        state: mounted

    - name: Change owner and group of local storage directory
      file:
        path: /k3s-local-storage
        group: "users"
        owner: "{{ ansible_user }}"
        recurse: true
        state: directory