network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.1.1/24
        dhcp4: false
        nameservers:
          addresses:
          - 1.1.1.1
  vlans:
    wan:
      id: 2
      link: eth0
      dhcp4: false # Because we will use PPPoE
