---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
  annotations:
    replicas-max: "1"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(10\.[0-9]+\.[0-9]+.*)$'
spec:
  releaseName: jellyfin
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jellyfin
    version: 2.0.1
  values:
    image:
      repository: linuxserver/jellyfin
      tag: 10.6.4-1-ls76
      pullPolicy: IfNotPresent
    # hostNetwork: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "jf.sko.ai"
      tls:
      - hosts:
        - "jf.sko.ai"
        secretName: ingress-cert-jellyfin
    advertiseIp: "http://192.168.1.24:32400"
    timezone: "Europe/London"
    persistence:
      config:
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
      movies:
        enabled: false
      tvshows:
        enabled: false
      extraExistingClaimMounts:
      - name: media
        mountPath: /media-pv
        existingClaim: nfs-media-pvc
    resources:
      requests:
        cpu: 35m
        memory: 1500Mi
      limits:
        memory: 3000Mi
