---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    replicas-max: "1"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.2
  values:
    image:
      repository: linuxserver/plex
      tag: latest
      pullPolicy: IfNotPresent
    # hostNetwork: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "plex.pi.sko.ai"
      tls:
      - hosts:
        - "plex.pi.sko.ai"
        secretName: ingress-cert-plex
    advertiseIp: "http://192.168.1.24:32400"
    timezone: "Europe/London"
    persistence:
      config:
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
      transcode:
        enabled: false
        emptyDir:
          medium: "Memory"
      data:
        enabled: false
    resources:
      requests:
        cpu: 35m
        memory: 1500Mi
      limits:
        memory: 3000Mi
